default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= Rails.application.credentials[Rails.env.to_sym][:mysql][:password] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: my_decks_development

test:
  <<: *default
  database: my_decks_test

production:
  <<: *default
  database: my_decks_production
  username: root
  password: <%= Rails.application.credentials[Rails.env.to_sym][:mysql][:password] %>
  socket: /var/lib/mysql/mysql.sock
